# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [2]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [3]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.93270766 0.11844117 0.63435245 ... 0.76351716 0.7506834  0.38724835]
 [0.58255929 0.6590486  0.83061211 ... 0.37443153 0.62584756 0.26459441]
 [0.48548685 0.1179765  0.63455351 ... 0.36729663 0.78794361 0.40575317]
 ...
 [0.87969858 0.51473907 0.16951397 ... 0.7188354  0.8654712  0.64773114]
 [0.46819662 0.48009953 0.34371738 ... 0.65946074 0.35036122 0.59552373]
 [0.71422295 0.77982191 0.99730301 ... 0.73830879 0.99834161 0.66416636]]
[[0.75512195 0.07424257 0.81767159 ... 0.0403261  0.3284023  0.85390146]
 [0.40016969 0.72827916 0.35359633 ... 0.09644778 0.26145288 0.62217733]
 [0.81274075 0.18908468 0.88882664 ... 0.18484789 0.12631329 0.12799676]
 ...
 [0.80511487 0.47037149 0.14386245 ... 0.58805256 0.5199566  0.71590655]
 [0.18151894 0.54659667 0.74766085 ... 0.64346048 0.28359841 0.93242676]
 [0.68465849 0.54514833 0.25263971 ... 0.49516194 0.27969085 0.05021879]]


Без использования numpy

In [1]:
def mult(a, b):
    n = len(a)
    result = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [4]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [5]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 816 ms, sys: 1.22 ms, total: 817 ms
Wall time: 916 ms


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 2.76 ms, sys: 3.08 ms, total: 5.84 ms
Wall time: 10.8 ms


In [7]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.4576784224118455e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [8]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.55873658 0.0165366  0.95033763] [0.35002242 0.63412018 0.75732374]


In [9]:
def scalar_product(a, b):
    result = 0
    for i in range(len(a)):
        result += a[i] * b[i]
    return result

In [10]:
def np_scalar_product(a, b):
    result = np.dot(a, b)
    return result

In [13]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 22 µs, sys: 0 ns, total: 22 µs
Wall time: 25 µs
CPU times: user 48 µs, sys: 0 ns, total: 48 µs
Wall time: 51.7 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** методы numpy оказываются эффективнее благодаря векторным операциям, которые гораздо быстрее последовательных. Из-за этого скорость вычислений в NumPy превосходит альтернативные решения без его использования в несколько раз.


------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [60]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  if len(a) > 0 and len(a[0]) == len(a):
    diagonal = np.diag(a)
    even_diagonal = diagonal[::2]
    return np.sum(even_diagonal)
  else:
      return 0

In [65]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[5, 8, 4, 8, 4],
       [2, 2, 3, 9, 3],
       [8, 3, 9, 4, 3],
       [6, 5, 1, 3, 5],
       [7, 6, 7, 2, 9]])

In [66]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 144 µs, sys: 18 µs, total: 162 µs
Wall time: 167 µs


23

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [69]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    X = np.array(A)
    cumulative_sums = np.cumsum(X, axis=1)
    result = cumulative_sums / np.arange(1, X.shape[1] + 1)
    return result

In [70]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[8.81576624e-01 5.00311152e-01 8.71683887e-01 1.22215388e-01
 9.24021929e-01 2.75256550e-01 4.72625258e-01 4.55072649e-01
 2.56006724e-01 5.67887118e-02 7.92528344e-01 8.70273141e-01
 6.40990595e-01 5.44548553e-01 4.98884132e-01 4.18075566e-02
 8.25527964e-01 4.69754346e-01 2.33660428e-01 3.92407287e-01
 1.96708071e-01 3.27334499e-01 3.36028259e-02 4.10110036e-01
 6.01143798e-01 5.78557431e-01 8.96040354e-01 1.74508350e-01
 2.88084429e-01 9.80428417e-01 9.65797280e-01 8.34487436e-01
 3.26500213e-01 8.68509191e-02 3.12087475e-01 9.60016376e-01
 2.19790331e-01 8.03910224e-02 8.24064290e-01 2.53319649e-01
 1.68940613e-01 6.50199168e-02 4.29556378e-01 1.22452337e-02
 1.49563542e-01 2.09856549e-01 1.58553070e-01 3.15008230e-01
 4.53656710e-01 8.74416421e-01 6.74575244e-01 1.02335457e-01
 3.49022468e-01 9.47780512e-01 4.99820555e-01 8.22460242e-01
 5.11073685e-01 6.50155672e-01 8.72588983e-01 6.70285710e-01
 2.38029802e-01 1.54312995e-01 2.53843217e-01 7.18352168e-01
 3.43361381e-01 7.031801

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [71]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    if len(a) == 0:
        return np.array([]), np.array([])
    current_element = a[0]
    count = 1
    encoded_elements = []
    repetitions = []
    for element in a[1:]:
        if element == current_element:
            count += 1
        else:
            encoded_elements.append(current_element)
            repetitions.append(count)

            current_element = element
            count = 1
    encoded_elements.append(current_element)
    repetitions.append(count)

    return np.array(encoded_elements), np.array(repetitions)

In [75]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
print(np_encode(X))

CPU times: user 37 µs, sys: 4 µs, total: 41 µs
Wall time: 45.5 µs
(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [76]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    transformed_X = X.copy()

    transformed_X[1::2] = a

    transformed_X[::2] = transformed_X[::2] ** 3

    reversed_transformed_X = transformed_X[::-1]

    result = np.concatenate((X, reversed_transformed_X))

    return result

In [78]:
X = np.array([i for i in range(1, 10, 2)])
print(X)
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)
print(np_transformation(X, 5))

[1 3 5 7 9]
CPU times: user 0 ns, sys: 126 µs, total: 126 µs
Wall time: 103 µs
[  1   3   5   7   9 729   5 125   5   1]
